"""Source handlers: local file scanning, web fetching, GitHub fetching/cloning."""

from __future__ import annotations

import hashlib
import logging
import os
import re
import subprocess
from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path

import requests
from bs4 import BeautifulSoup
from markdownify import markdownify as md

from repo_rag.chunker import detect_language, is_code_file
from repo_rag.config import GitHubSource, LocalSource, WebSource

logger = logging.getLogger(__name__)

# ── Constants ────────────────────────────────────────────────────────────

MIN_FILE_SIZE = 100  # bytes
MAX_FILE_SIZE = 50_000  # 50 KB

SKIP_DIRS = {
    ".git", "node_modules", "bin", "obj", ".vs", ".idea",
    "vendor", "build", "dist", "target", "out", "packages",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "coverage", ".nyc_output", "artifacts", ".next", ".nuxt",
    ".venv", "venv", "env", ".tox", ".eggs",
}

AUTO_GENERATED_MARKERS = [
    "// <auto-generated",
    "# auto-generated",
    "/* auto-generated",
    "// this file is generated",
    "# this file is generated",
]

DOC_FILES = ["README.md", "readme.md", "docs/README.md", "CONTRIBUTING.md"]

USER_AGENT = "repo-rag/0.1 (codebase indexer)"


# ── Document model ───────────────────────────────────────────────────────


@dataclass
class RawDocument:
    """A document before chunking."""

    content: str
    source: str  # file path or URL
    source_type: str  # local_code, local_doc, web, github_code, github_doc
    title: str
    file_path: str  # relative path within project
    language: str | None = None
    tags: list[str] = field(default_factory=list)
    repo: str | None = None  # e.g. "owner/repo" for github sources


# ── Local file scanner ───────────────────────────────────────────────────


class LocalScanner:
    """Scan local directory for code and doc files matching include/exclude patterns."""

    def __init__(self, source: LocalSource, project_dir: Path):
        self.source = source
        self.root = (project_dir / source.path).resolve()

    def scan(self) -> list[RawDocument]:
        """Walk the directory tree and collect matching files."""
        docs: list[RawDocument] = []
        if not self.root.is_dir():
            logger.warning("Source path does not exist: %s", self.root)
            return docs

        for dirpath, dirnames, filenames in os.walk(self.root):
            # Filter out skip dirs (modify in-place to prune walk)
            dirnames[:] = [
                d for d in dirnames
                if d not in SKIP_DIRS and not self._matches_exclude(d)
            ]

            for fname in filenames:
                fpath = Path(dirpath) / fname
                rel_path = str(fpath.relative_to(self.root))

                if not self._matches_include(fname):
                    continue
                if self._matches_exclude(rel_path):
                    continue

                # Size filters
                try:
                    size = fpath.stat().st_size
                except OSError:
                    continue
                if size < MIN_FILE_SIZE or size > MAX_FILE_SIZE:
                    continue

                # Read content
                try:
                    content = fpath.read_text(encoding="utf-8", errors="replace")
                except Exception as e:
                    logger.debug("Failed to read %s: %s", fpath, e)
                    continue

                # Skip auto-generated files
                if self._is_auto_generated(content):
                    continue

                lang = detect_language(rel_path)
                source_type = "local_code" if is_code_file(rel_path) else "local_doc"

                docs.append(RawDocument(
                    content=content,
                    source=rel_path,
                    source_type=source_type,
                    title=rel_path,
                    file_path=rel_path,
                    language=lang,
                    tags=[],
                ))

        logger.info("Scanned %d files from %s", len(docs), self.root)
        return docs

    def _matches_include(self, filename: str) -> bool:
        return any(fnmatch(filename, pat) for pat in self.source.include)

    def _matches_exclude(self, path: str) -> bool:
        return any(fnmatch(path, pat) or fnmatch(Path(path).name, pat)
                    for pat in self.source.exclude)

    @staticmethod
    def _is_auto_generated(content: str) -> bool:
        first_lines = content[:500].lower()
        return any(marker.lower() in first_lines for marker in AUTO_GENERATED_MARKERS)


# ── Web fetcher ──────────────────────────────────────────────────────────


class WebFetcher:
    """Fetch and extract content from web URLs with local caching."""

    def __init__(self, cache_dir: Path):
        self.cache_dir = cache_dir / "web"
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    def fetch(self, source: WebSource) -> RawDocument | None:
        """Fetch a URL, extract main content, convert to markdown."""
        cached_path = self.cache_dir / self._url_to_filename(source.url)

        # Use cache if available
        if cached_path.exists():
            content = cached_path.read_text()
            title = content.split("\n")[0].lstrip("# ").strip() if content else source.url
            return RawDocument(
                content=content,
                source=source.url,
                source_type="web",
                title=title,
                file_path=source.url,
                tags=source.tags,
            )

        try:
            resp = requests.get(
                source.url,
                headers={"User-Agent": USER_AGENT},
                timeout=30,
            )
            resp.raise_for_status()
        except Exception as e:
            logger.warning("Failed to fetch %s: %s", source.url, e)
            return None

        soup = BeautifulSoup(resp.text, "html.parser")

        # Remove noise
        for tag in soup.find_all(["script", "style", "nav", "footer", "header", "aside"]):
            tag.decompose()

        # Find main content area
        main = (
            soup.find("article")
            or soup.find("main")
            or soup.find("div", class_=re.compile(r"content|post|article|entry", re.I))
            or soup.find("body")
        )
        if not main:
            logger.warning("No main content found for %s", source.url)
            return None

        title_tag = soup.find("title")
        title = title_tag.get_text(strip=True) if title_tag else source.url

        content_md = md(str(main), heading_style="ATX", strip=["img"])
        content_md = re.sub(r"\n{3,}", "\n\n", content_md).strip()
        full_content = f"# {title}\n\nSource: {source.url}\n\n{content_md}"

        cached_path.write_text(full_content)

        return RawDocument(
            content=full_content,
            source=source.url,
            source_type="web",
            title=title,
            file_path=source.url,
            tags=source.tags,
        )

    @staticmethod
    def _url_to_filename(url: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9]", "_", url)[:80]
        url_hash = hashlib.md5(url.encode()).hexdigest()[:8]
        return f"{slug}_{url_hash}.md"


# ── GitHub fetcher ───────────────────────────────────────────────────────


class GitHubFetcher:
    """Fetch READMEs and optionally clone repos for code indexing."""

    def __init__(self, cache_dir: Path):
        self.cache_dir = cache_dir / "github"
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.clone_dir = cache_dir / "repos"
        self.clone_dir.mkdir(parents=True, exist_ok=True)

    def fetch_readme(self, source: GitHubSource) -> RawDocument | None:
        """Fetch README and combine doc files from a GitHub repo."""
        owner, repo = self._parse_url(source.url)
        repo_cache = self.cache_dir / f"{owner}_{repo}"
        cached_path = repo_cache / "combined.md"

        if cached_path.exists():
            content = cached_path.read_text()
            return RawDocument(
                content=content,
                source=source.url,
                source_type="github_doc",
                title=f"{owner}/{repo}",
                file_path=f"{owner}/{repo}/README.md",
                tags=source.tags,
                repo=f"{owner}/{repo}",
            )

        repo_cache.mkdir(parents=True, exist_ok=True)

        # Fetch repo info
        info = self._fetch_repo_info(owner, repo)
        desc = info.get("description", "") if info else ""
        stars = info.get("stargazers_count", 0) if info else 0
        lang = info.get("language", "") if info else ""

        # Fetch doc files
        collected = []
        for filepath in DOC_FILES:
            content = self._fetch_raw_file(owner, repo, filepath)
            if content:
                collected.append((filepath, content))

        if not collected:
            logger.warning("No docs found for %s", source.url)
            return None

        header = f"# {owner}/{repo}\n\n- URL: {source.url}\n- Description: {desc}\n- Stars: {stars}\n- Language: {lang}\n\n---\n\n"
        combined = header
        for filepath, content in collected:
            combined += f"\n\n## File: {filepath}\n\n{content}\n"

        if len(combined) > 15000:
            combined = combined[:15000] + "\n\n[... truncated ...]"

        cached_path.write_text(combined)

        return RawDocument(
            content=combined,
            source=source.url,
            source_type="github_doc",
            title=f"{owner}/{repo}",
            file_path=f"{owner}/{repo}/README.md",
            tags=source.tags,
            repo=f"{owner}/{repo}",
        )

    def clone_and_scan(self, source: GitHubSource) -> list[RawDocument]:
        """Shallow-clone the repo and scan for code files."""
        owner, repo = self._parse_url(source.url)
        repo_dir = self.clone_dir / f"{owner}_{repo}"

        # Clone or pull
        if not (repo_dir / ".git").exists():
            logger.info("Cloning %s/%s ...", owner, repo)
            try:
                subprocess.run(
                    ["git", "clone", "--depth", "1", "--single-branch", source.url, str(repo_dir)],
                    capture_output=True, timeout=120, check=True,
                )
            except Exception as e:
                logger.warning("Failed to clone %s: %s", source.url, e)
                return []

        # Build a LocalScanner-like scan but with GitHub metadata
        docs: list[RawDocument] = []
        scan_roots = [repo_dir / p for p in source.code_paths] if source.code_paths else [repo_dir]

        for scan_root in scan_roots:
            if not scan_root.is_dir():
                continue
            for dirpath, dirnames, filenames in os.walk(scan_root):
                dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]

                for fname in filenames:
                    fpath = Path(dirpath) / fname
                    lang = detect_language(fname)
                    if not lang or not is_code_file(fname):
                        continue

                    try:
                        size = fpath.stat().st_size
                    except OSError:
                        continue
                    if size < MIN_FILE_SIZE or size > MAX_FILE_SIZE:
                        continue

                    try:
                        content = fpath.read_text(encoding="utf-8", errors="replace")
                    except Exception:
                        continue

                    # Skip auto-generated
                    if any(m.lower() in content[:500].lower() for m in AUTO_GENERATED_MARKERS):
                        continue

                    rel_path = str(fpath.relative_to(repo_dir))
                    github_url = f"{source.url}/blob/main/{rel_path}"

                    docs.append(RawDocument(
                        content=content,
                        source=github_url,
                        source_type="github_code",
                        title=f"{owner}/{repo}: {rel_path}",
                        file_path=rel_path,
                        language=lang,
                        tags=source.tags + [lang] if lang else source.tags,
                        repo=f"{owner}/{repo}",
                    ))

        logger.info("Scanned %d code files from %s/%s", len(docs), owner, repo)
        return docs

    @staticmethod
    def _parse_url(url: str) -> tuple[str, str]:
        parts = url.rstrip("/").split("/")
        return parts[-2], parts[-1]

    @staticmethod
    def _fetch_raw_file(owner: str, repo: str, filepath: str) -> str | None:
        url = f"https://raw.githubusercontent.com/{owner}/{repo}/HEAD/{filepath}"
        try:
            resp = requests.get(url, timeout=15)
            if resp.status_code == 200:
                return resp.text
        except Exception:
            pass
        return None

    @staticmethod
    def _fetch_repo_info(owner: str, repo: str) -> dict | None:
        url = f"https://api.github.com/repos/{owner}/{repo}"
        try:
            resp = requests.get(
                url, timeout=15,
                headers={"Accept": "application/vnd.github.v3+json"},
            )
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass
        return None
